#ifndef _pq_XTcu_idl_
#define _pq_XTcu_idl_

#include <com/sun/star/uno/XInterface.idl>

module pq {
	interface XTcu {
		sequence <string> treelines([in] any Object);
		sequence <string> wtreelines([in] any Object);
		sequence <string> wcomparelines([in] any Object1, [in] any Object2);
		void wtree([in] any Object);
		void wcompare([in] any Object1, [in] any Object2);
	};
};

#endif