#ifndef _pq_XTcu_idl_
#define _pq_XTcu_idl_

#include <com/sun/star/uno/XInterface.idl>

module pq {
	interface XTcu {
		sequence <string> tree([in] any Object);
		void wtree([in] any Object);
	};
};

#endif